#!/bin/sh
cp mk.sh linux/mk.sh
cp mkmenu.sh linux/mkmenu.sh
cp mpc8308erdb.dts linux/arch/powerpc/boot/dts/mpc8308erdb.dts
cp legacy_serial.c linux/arch/powerpc/kernel/legacy_serial.c

# tmp
cp 8250org.c linux/drivers/serial/8250.c
cp serial_core000.c linux/drivers/serial/serial_core.c

cp c linux/.config
cp Makefile linux/Makefile

# bug reboot fix 
cp setup-common.c linux/arch/powerpc/kernel/setup-common.c

cp misc.c linux/arch/powerpc/platforms/83xx/misc.c
