#!/bin/bash
cp Makefile uboot/board/ads5121/Makefile
cp ads5121.c uboot/board/ads5121/ads5121.c
cp ads5121.h uboot/include/configs/ads5121.h
#cp start.S uboot/cpu/mpc512x/start.S
#cp serial.c uboot/cpu/mpc512x/serial.c
#cp cpu_init.c uboot/cpu/mpc512x/cpu_init.c
cp flash.c uboot/board/ads5121/flash.c
cp intel_flash.c uboot/board/ads5121/intel_flash.c
cp intel_flash.h uboot/board/ads5121/intel_flash.h
cp board.c uboot/lib_ppc/board.c
cp fsl_nfc_nand.c uboot/drivers/mtd/nand/fsl_nfc_nand.c
#  NFC_DIV
cp cpu_init.c uboot/cpu/mpc512x/cpu_init.c
cp mpc512x.h uboot/include/mpc512x.h
# i2c test , rm ack
cp i2c000.c uboot/cpu/mpc512x/i2c.c
