#!/bin/sh
cp mx51_babbage.c linux/arch/arm/mach-mx5/
cp mx51_babbage_pmic_mc13892.c linux/arch/arm/mach-mx5/
cp mx51_pins_my.h linux/arch/arm/mach-mx5/
cp iomux-mx51.h linux/arch/arm/plat-mxc/include/mach/
cp smsc.c linux/drivers/net/phy/
cp fec.c linux/drivers/net/
